# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipe.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npipe.proto\"\x1a\n\x0bPipeRequest\x12\x0b\n\x03new\x18\x01 \x03(\x0c\"\x18\n\tPipeReply\x12\x0b\n\x03\x61ns\x18\x01 \x03(\x08\x32\x35\n\nPipeServer\x12\'\n\tinference\x12\x0c.PipeRequest\x1a\n.PipeReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PIPEREQUEST']._serialized_start=14
  _globals['_PIPEREQUEST']._serialized_end=40
  _globals['_PIPEREPLY']._serialized_start=42
  _globals['_PIPEREPLY']._serialized_end=66
  _globals['_PIPESERVER']._serialized_start=68
  _globals['_PIPESERVER']._serialized_end=121
# @@protoc_insertion_point(module_scope)
